container:
  image: python:slim

test_task:
  matrix:
    - container:
        image: python:3.6
    - allow_failures: true
      container:
        image: python:2.7
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: pip install -r requirements.txt
  test_script: pytest
